// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import { Address, DataSourceTemplate } from "@graphprotocol/graph-ts";

export class ZkAsset extends DataSourceTemplate {
  static create(address: Address): void {
    DataSourceTemplate.create("ZkAsset", [address.toHex()]);
  }
}
