// auto-generated by @aztec/guacamole-ui
export const buttonThemeMap = {
  primary: 'primary',
  secondary: 'primary-lighter',
  white: 'white',
};
export const buttonSizeMap = {
  xxs: '20px',
  xs: '24px',
  s: '28px',
  m: '32px',
  l: '44px',
  xl: '48px',
  xxl: '56px',
};
export const buttonTextSizeMap = {
  xxs: 'xxs',
  xs: 'xs',
  s: 's',
  m: 's',
  l: 's',
  xl: 's',
  xxl: 's',
};
export const buttonSpacingHSizeMap = {
  xxs: 'm',
  xs: 'm',
  s: 'l',
  m: 'xl',
  l: 'xl',
  xl: 'xl',
  xxl: 'xl',
};
export const buttonBorderWidth = '1px';
export const outlinedButtonBorderWidth = '2px';
export const colorMap = {
  primary: '#808dff',
  'primary-light': 'rgba(137, 139, 246, 0.7)',
  'primary-lighter': 'rgba(137, 139, 246, 0.45)',
  'primary-lightest': 'rgb(244, 245, 254)',
  black: '#000000',
  'grey-darker': 'rgba(0, 0, 0, 0.85)',
  'grey-dark': 'rgba(0, 0, 0, 0.7)',
  grey: 'rgba(0, 0, 0, 0.45)',
  'grey-light': 'rgba(0, 0, 0, 0.2)',
  'grey-lighter': 'rgba(0, 0, 0, 0.1)',
  'grey-lightest': '#F9fbfd',
  white: '#FFFFFF',
  'white-light': 'rgba(255, 255, 255, 0.85)',
  'white-lighter': 'rgba(255, 255, 255, 0.5)',
  'white-lightest': 'rgba(255,255,255,0.3)',
  transparent: 'rgba(255, 255, 255, 0)',
  secondary: '#17173C',
  'secondary-light': '#222261',
  'secondary-lighter': 'rgba(74,144,226, 0.3)',
  'secondary-lightest': 'rgba(74,144,226, 0.1)',
  pink: '#F7B2D1',
  red: '#F23A5B',
  purple: '#49098A',
  blue: '#2772CE',
  green: '#41BA00',
  yellow: '#FACB00',
  orange: '#E57300',
  brown: '#49311A',
};
export const darkBackgroundColors = [
  'primary',
  'primary-light',
  'primary-lighter',
  'secondary',
  'secondary-light',
  'black',
  'grey-darker',
  'grey-dark',
  'grey',
  'red',
  'purple',
  'blue',
  'green',
  'orange',
  'brown',
  'white-lightest',
];
export const defaultShadowColorName = 'grey-lighter';
export const defaultShadowColor = 'rgba(0, 0, 0, 0.1)';
export const defaultBorderColorName = 'grey-lighter';
export const defaultBorderColor = 'rgba(0, 0, 0, 0.1)';
export const defaultHoverBackgroundColorName = 'grey-lightest';
export const defaultHoverBackgroundColor = '#F9fbfd';
export const defaultTextColorName = 'grey-darker';
export const defaultTextColor = '#221635';
export const defaultLabelColorName = 'grey';
export const defaultLabelColor = '#9699BA';
export const defaultLinkColorName = 'secondary';
export const defaultLinkColor = '#898BF6';
export const overlayThemeBgMap = {
  primary: 'primary-lightest',
  secondary: 'secondary-lightest',
  white: 'white-lighter',
};
export const svgProgressThemeBgMap = {
  primary: 'primary-lightest',
  secondary: 'secondary-lightest',
  white: 'white-lighter',
};
export const iconSizeMap = {
  xxs: '12px',
  xs: '14px',
  s: '16px',
  m: '18px',
  l: '24px',
  xl: '36px',
  xxl: '48px',
};
export const inputSizeMap = {
  xs: '24px',
  s: '28px',
  m: '32px',
  l: '40px',
};
export const inputFontSizeKeyMap = {
  xs: 'xxs',
  s: 'xxs',
  m: 'xs',
  l: 'xs',
};
export const inputBorderWidth = '1px';
export const defaultInputBgColorName = 'white';
export const defaultInputBgColor = '#FFFFFF';
export const defaultInputOutlineColorName = 'grey-light';
export const defaultInputOutlineColor = '#fff';
export const defaultInputActiveBgColorName = 'white';
export const defaultInputActiveBgColor = '#FFFFFF';
export const defaultInputActiveOutlineColorName = 'secondary-light';
export const defaultInputActiveOutlineColor = '#fff';
export const defaultInputValueColorName = 'grey-dark';
export const defaultInputValueColor = 'rgba(0, 0, 0, 0.7)';
export const defaultInputPlaceholderColorName = 'grey-light';
export const defaultInputPlaceholderColor = 'rgba(0, 0, 0, 0.2)';
export const darkInputBgColorName = 'transparent';
export const darkInputBgColor = 'rgba(255, 255, 255, 0)';
export const darkInputOutlineColorName = 'white-light';
export const darkInputOutlineColor = 'rgba(255, 255, 255, 0.85)';
export const darkInputActiveBgColorName = 'transparent';
export const darkInputActiveBgColor = 'rgba(255, 255, 255, 0)';
export const darkInputActiveOutlineColorName = 'white';
export const darkInputActiveOutlineColor = '#FFFFFF';
export const darkInputValueColorName = 'white';
export const darkInputValueColor = '#FFFFFF';
export const darkInputPlaceholderColorName = 'white-lighter';
export const darkInputPlaceholderColor = 'rgba(255, 255, 255, 0.5)';
export const inlineInputBgColorName = 'grey-lightest';
export const inlineInputBgColor = '#F9fbfd';
export const inlineInputActiveBgColorName = 'grey-lightest';
export const inlineInputActiveBgColor = '#F9fbfd';
export const inlineInputActiveOutlineColorName = 'secondary-light';
export const inlineInputActiveOutlineColor = '#222261';
export const inlineInputValueColorName = 'grey-dark';
export const inlineInputValueColor = 'rgba(0, 0, 0, 0.7)';
export const inlineInputPlaceholderColorName = 'grey-light';
export const inlineInputPlaceholderColor = 'rgba(0, 0, 0, 0.2)';
export const errorInputColorName = 'red';
export const errorInputColor = '#F23A5B';
export const focusInputColorName = 'secondary-light';
export const focusInputColor = '#222261';
export const deviceBreakpointMap = {
  xxl: '2000px',
  xl: '1440px',
  l: '1220px',
  m: '960px',
  s: '768px',
  xs: '480px',
  xxs: '0',
};
export const minDeviceWidthXxl = '2000px';
export const minDeviceWidthXl = '1440px';
export const minDeviceWidthL = '1220px';
export const minDeviceWidthM = '960px';
export const minDeviceWidthS = '768px';
export const minDeviceWidthXs = '480px';
export const minDeviceWidthXxs = '0';
export const spacingMap = {
  xxs: '2px',
  xs: '4px',
  s: '8px',
  m: '12px',
  l: '16px',
  xl: '24px',
  xxl: '36px',
};
export const pageSpacingKeyMap = {
  xxl: 'xxl',
  xl: 'xxl',
  l: 'xxl',
  m: 'xxl',
  s: 'xl',
  xs: 'xl',
  xxs: 'xl',
};
export const defaultSpacingKeyMap = {
  xxl: 'xl',
  xl: 'xl',
  l: 'l',
  m: 'l',
  s: 'l',
  xs: 'm',
  xxs: 'm',
};
export const listItemIconSizeMap = {
  xxs: 'xxs',
  xs: 'xs',
  s: 's',
  m: 'm',
  l: 'l',
  xl: 'xl',
  xxl: 'xl',
};
export const listItemAvatarTextSizeMap = {
  xxs: 'xs',
  xs: 's',
  s: 'm',
  m: 'l',
  l: 'xl',
  xl: 'xxl',
  xxl: 'xxl',
};
export const roundedCornerMap = {
  none: '0',
  xxs: '2px',
  xs: '4px',
  s: '6px',
  m: '8px',
  l: '12px',
  circular: '100%',
};
export const avatarSizesMap = {
  xxs: '20px',
  xs: '24px',
  s: '32px',
  m: '40px',
  l: '48px',
  xl: '56px',
  xxl: '72px',
};
export const avatarTextSizeMap = {
  xxs: 'xxs',
  xs: 'xxs',
  s: 'xxs',
  m: 'xs',
  l: 'm',
  xl: 'l',
  xxl: 'xl',
};
export const badgeSizeMap = {
  xxs: '16px',
  xs: '20px',
  s: '24px',
  m: '28px',
  l: '32px',
  xl: '36px',
  xxl: '48px',
};
export const defaultFontFamily = '\'Gill Sans\', sans-serif';
export const fontSizeMap = {
  xxs: '12px',
  xs: '14px',
  s: '16px',
  m: '18px',
  l: '24px',
  xl: '28px',
  xxl: '34px',
};
export const lineHeightMap = {
  xxs: '18px',
  xs: '20px',
  s: '24px',
  m: '28px',
  l: '32px',
  xl: '40px',
  xxl: '48px',
};
export const fontWeightMap = {
  light: 300,
  normal: 400,
  medium: 500,
  semibold: 600,
  bold: 700,
};
export const calendarBgName = 'white';
export const calendarBg = '#FFFFFF';
export const calendarMonthWidth = '319px';
export const calendarMonthPaddingSizeKey = 'l';
export const calendarMonthFontSizeKey = 'm';
export const calendarWeekFontSizeKey = 'xs';
export const calendarWeekColorName = 'grey';
export const calendarWeekColor = 'rgba(0, 0, 0, 0.45)';
export const calendarDayWidth = '41px';
export const calendarDayHeight = '41px';
export const calendarDayFontSizeKey = 's';
export const calendarHoveredColorName = 'grey-darker';
export const calendarHoveredColor = 'rgba(0, 0, 0, 0.85)';
export const calendarHoveredBgName = 'secondary-lightest';
export const calendarHoveredBg = 'rgba(74,144,226, 0.1)';
export const calendarSelectedColorName = 'white';
export const calendarSelectedColor = '#FFFFFF';
export const calendarSelectedBgName = 'secondary';
export const calendarSelectedBg = '#17173C';
export const calendarInRangeBgName = 'secondary-lightest';
export const calendarInRangeBg = 'rgba(74,144,226, 0.1)';
export const calendarOutsideColorName = 'grey';
export const calendarOutsideColor = 'rgba(0, 0, 0, 0.45)';
export const buttonSizeKeys = [
  'xxs',
  'xs',
  's',
  'm',
  'l',
  'xl',
  'xxl',
];
export const colorNames = [
  'primary',
  'primary-light',
  'primary-lighter',
  'primary-lightest',
  'black',
  'grey-darker',
  'grey-dark',
  'grey',
  'grey-light',
  'grey-lighter',
  'grey-lightest',
  'white',
  'white-light',
  'white-lighter',
  'white-lightest',
  'transparent',
  'secondary',
  'secondary-light',
  'secondary-lighter',
  'secondary-lightest',
  'pink',
  'red',
  'purple',
  'blue',
  'green',
  'yellow',
  'orange',
  'brown',
];
export const backgroundNames = [
  'primary',
  'primary-light',
  'primary-lighter',
  'primary-lightest',
  'black',
  'grey-darker',
  'grey-dark',
  'grey',
  'grey-light',
  'grey-lighter',
  'grey-lightest',
  'white',
  'white-light',
  'white-lighter',
  'white-lightest',
  'transparent',
  'secondary',
  'secondary-light',
  'secondary-lighter',
  'secondary-lightest',
  'pink',
  'red',
  'purple',
  'blue',
  'green',
  'yellow',
  'orange',
  'brown',
];
export const textColorNames = [
  'primary',
  'primary-light',
  'primary-lighter',
  'primary-lightest',
  'black',
  'grey-darker',
  'grey-dark',
  'grey',
  'grey-light',
  'grey-lighter',
  'grey-lightest',
  'white',
  'white-light',
  'white-lighter',
  'white-lightest',
  'transparent',
  'secondary',
  'secondary-light',
  'secondary-lighter',
  'secondary-lightest',
  'pink',
  'red',
  'purple',
  'blue',
  'green',
  'yellow',
  'orange',
  'brown',
  'default',
  'label',
];
export const overlayThemeNames = [
  'primary',
  'secondary',
  'white',
];
export const defaultInputSizeKey = 'm';
export const inputSizeKeys = [
  'xs',
  's',
  'm',
  'l',
];
export const inputThemeNames = [
  'default',
  'inline',
  'dark',
];
export const inputStatusNames = [
  'error',
  'focus',
];
export const deviceBreakpointKeys = [
  'xxl',
  'xl',
  'l',
  'm',
  's',
  'xs',
  'xxs',
];
export const defaultDeviceBreakpointKey = 'xxs';
export const sizeKeys = [
  'xxs',
  'xs',
  's',
  'm',
  'l',
  'xl',
  'xxl',
];
export const defaultSize = '8px';
export const maxGridColumns = 12;
export const roundedCornerKeys = [
  'none',
  'xxs',
  'xs',
  's',
  'm',
  'l',
  'circular',
];
export const defaultRoundedCornerKey = 'xs';
export const shadowLayerKeys = [
  0,
  1,
  2,
  3,
];
export const imageRatioNames = [
  'square',
  'classic',
  'golden',
  'landscape',
  'ultra',
];
export const shapeSizeKeys = [
  'xxs',
  'xs',
  's',
  'm',
  'l',
  'xl',
  'xxl',
];
export const iconRotateDegrees = [
  0,
  90,
  180,
  270,
];
export const fontSizeKeys = [
  'xxs',
  'xs',
  's',
  'm',
  'l',
  'xl',
  'xxl',
];
export const defaultFontSizeKey = 'xs';
export const fontWeightKeys = [
  'inherit',
  'light',
  'normal',
  'medium',
  'semibold',
  'bold',
];
export const specialTextColorNames = [
  'default',
  'label',
];
