export const ADDRESS_LENGTH = 42;

export const USER_PUBLIC_KEY_LENGTH = 120;
export const EXTENSION_PUBLIC_KEY_LENGTH = 180;
export const PUBLIC_KEY_SECP256K1_LENGTH = 120;
export const PUBLIC_KEY_CURVE25519_LENGTH = 180;

export const VIEWING_KEY_LENGTH = 5;

export const METADATA_AZTEC_DATA_LENGTH = 192;
export const METADATA_VAR_LEN_LENGTH = 32;
