// exluding 0x
export const ADDRESS_LENGTH = 40;

export const USER_PUBLIC_KEY_LENGTH = 66;
export const EXTENSION_PUBLIC_KEY_LENGTH = 64;

export const REAL_VIEWING_KEY_LENGTH = 138;
export const VIEWING_KEY_LENGTH = 420;

export const METADATA_AZTEC_DATA_LENGTH = 194;
export const AZTEC_JS_DEFAULT_METADATA_PREFIX_LENGTH = 66;
export const AZTEC_JS_METADATA_PREFIX_LENGTH = 130;

export const START_EVENTS_SYNCING_BLOCK = 0;

export const INFURA_API_KEY = '09c4eed231c840d5ace14ba5389a1a7c';

export const NOTE_STATUS = {
    CREATED: 'CREATED',
    DESTROYED: 'DESTROYED',
};
