// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  EthereumCall,
  EthereumEvent,
  SmartContract,
  EthereumValue,
  JSONValue,
  TypedMap,
  Entity,
  EthereumTuple,
  Bytes,
  Address,
  BigInt
} from "@graphprotocol/graph-ts";

export class UpdateTotalBurned extends EthereumEvent {
  get params(): UpdateTotalBurned__Params {
    return new UpdateTotalBurned__Params(this);
  }
}

export class UpdateTotalBurned__Params {
  _event: UpdateTotalBurned;

  constructor(event: UpdateTotalBurned) {
    this._event = event;
  }

  get noteHash(): Bytes {
    return this._event.parameters[0].value.toBytes();
  }

  get noteData(): Bytes {
    return this._event.parameters[1].value.toBytes();
  }
}

export class UpdateTotalMinted extends EthereumEvent {
  get params(): UpdateTotalMinted__Params {
    return new UpdateTotalMinted__Params(this);
  }
}

export class UpdateTotalMinted__Params {
  _event: UpdateTotalMinted;

  constructor(event: UpdateTotalMinted) {
    this._event = event;
  }

  get noteHash(): Bytes {
    return this._event.parameters[0].value.toBytes();
  }

  get metaData(): Bytes {
    return this._event.parameters[1].value.toBytes();
  }
}

export class OwnershipTransferred extends EthereumEvent {
  get params(): OwnershipTransferred__Params {
    return new OwnershipTransferred__Params(this);
  }
}

export class OwnershipTransferred__Params {
  _event: OwnershipTransferred;

  constructor(event: OwnershipTransferred) {
    this._event = event;
  }

  get previousOwner(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get newOwner(): Address {
    return this._event.parameters[1].value.toAddress();
  }
}

export class CreateNoteRegistry extends EthereumEvent {
  get params(): CreateNoteRegistry__Params {
    return new CreateNoteRegistry__Params(this);
  }
}

export class CreateNoteRegistry__Params {
  _event: CreateNoteRegistry;

  constructor(event: CreateNoteRegistry) {
    this._event = event;
  }

  get zkAssetAddress(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get linkedTokenAddress(): Address {
    return this._event.parameters[1].value.toAddress();
  }

  get scalingFactor(): BigInt {
    return this._event.parameters[2].value.toBigInt();
  }

  get canAdjustSupply(): boolean {
    return this._event.parameters[3].value.toBoolean();
  }

  get canConvert(): boolean {
    return this._event.parameters[4].value.toBoolean();
  }
}

export class CreateZkAsset extends EthereumEvent {
  get params(): CreateZkAsset__Params {
    return new CreateZkAsset__Params(this);
  }
}

export class CreateZkAsset__Params {
  _event: CreateZkAsset;

  constructor(event: CreateZkAsset) {
    this._event = event;
  }

  get aceAddress(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get linkedTokenAddress(): Address {
    return this._event.parameters[1].value.toAddress();
  }

  get scalingFactor(): BigInt {
    return this._event.parameters[2].value.toBigInt();
  }

  get _canAdjustSupply(): boolean {
    return this._event.parameters[3].value.toBoolean();
  }

  get _canConvert(): boolean {
    return this._event.parameters[4].value.toBoolean();
  }
}

export class ApprovedAddress extends EthereumEvent {
  get params(): ApprovedAddress__Params {
    return new ApprovedAddress__Params(this);
  }
}

export class ApprovedAddress__Params {
  _event: ApprovedAddress;

  constructor(event: ApprovedAddress) {
    this._event = event;
  }

  get addressApproved(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get noteHash(): Bytes {
    return this._event.parameters[1].value.toBytes();
  }
}

export class CreateNoteRegistry1 extends EthereumEvent {
  get params(): CreateNoteRegistry1__Params {
    return new CreateNoteRegistry1__Params(this);
  }
}

export class CreateNoteRegistry1__Params {
  _event: CreateNoteRegistry1;

  constructor(event: CreateNoteRegistry1) {
    this._event = event;
  }

  get noteRegistryId(): BigInt {
    return this._event.parameters[0].value.toBigInt();
  }
}

export class CreateNote extends EthereumEvent {
  get params(): CreateNote__Params {
    return new CreateNote__Params(this);
  }
}

export class CreateNote__Params {
  _event: CreateNote;

  constructor(event: CreateNote) {
    this._event = event;
  }

  get owner(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get noteHash(): Bytes {
    return this._event.parameters[1].value.toBytes();
  }

  get metadata(): Bytes {
    return this._event.parameters[2].value.toBytes();
  }
}

export class DestroyNote extends EthereumEvent {
  get params(): DestroyNote__Params {
    return new DestroyNote__Params(this);
  }
}

export class DestroyNote__Params {
  _event: DestroyNote;

  constructor(event: DestroyNote) {
    this._event = event;
  }

  get owner(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get noteHash(): Bytes {
    return this._event.parameters[1].value.toBytes();
  }

  get metadata(): Bytes {
    return this._event.parameters[2].value.toBytes();
  }
}

export class ConvertTokens extends EthereumEvent {
  get params(): ConvertTokens__Params {
    return new ConvertTokens__Params(this);
  }
}

export class ConvertTokens__Params {
  _event: ConvertTokens;

  constructor(event: ConvertTokens) {
    this._event = event;
  }

  get owner(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get value(): BigInt {
    return this._event.parameters[1].value.toBigInt();
  }
}

export class RedeemTokens extends EthereumEvent {
  get params(): RedeemTokens__Params {
    return new RedeemTokens__Params(this);
  }
}

export class RedeemTokens__Params {
  _event: RedeemTokens;

  constructor(event: RedeemTokens) {
    this._event = event;
  }

  get owner(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get value(): BigInt {
    return this._event.parameters[1].value.toBigInt();
  }
}

export class UpdateNoteMetaData extends EthereumEvent {
  get params(): UpdateNoteMetaData__Params {
    return new UpdateNoteMetaData__Params(this);
  }
}

export class UpdateNoteMetaData__Params {
  _event: UpdateNoteMetaData;

  constructor(event: UpdateNoteMetaData) {
    this._event = event;
  }

  get owner(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get noteHash(): Bytes {
    return this._event.parameters[1].value.toBytes();
  }

  get metadata(): Bytes {
    return this._event.parameters[2].value.toBytes();
  }
}

export class ZkAssetTemplate extends SmartContract {
  static bind(address: Address): ZkAssetTemplate {
    return new ZkAssetTemplate("ZkAssetTemplate", address);
  }

  JOIN_SPLIT_PROOF(): i32 {
    let result = super.call("JOIN_SPLIT_PROOF", []);
    return result[0].toI32();
  }

  ZERO_VALUE_NOTE_HASH(): Bytes {
    let result = super.call("ZERO_VALUE_NOTE_HASH", []);
    return result[0].toBytes();
  }

  PUBLIC_RANGE_PROOF(): i32 {
    let result = super.call("PUBLIC_RANGE_PROOF", []);
    return result[0].toI32();
  }

  confidentialApproved(param0: Bytes, param1: Address): boolean {
    let result = super.call("confidentialApproved", [
      EthereumValue.fromFixedBytes(param0),
      EthereumValue.fromAddress(param1)
    ]);
    return result[0].toBoolean();
  }

  PRIVATE_RANGE_PROOF(): i32 {
    let result = super.call("PRIVATE_RANGE_PROOF", []);
    return result[0].toI32();
  }

  proofs(param0: i32): BigInt {
    let result = super.call("proofs", [EthereumValue.fromI32(param0)]);
    return result[0].toBigInt();
  }

  supportsProof(_proof: i32): boolean {
    let result = super.call("supportsProof", [EthereumValue.fromI32(_proof)]);
    return result[0].toBoolean();
  }

  DIVIDEND_PROOF(): i32 {
    let result = super.call("DIVIDEND_PROOF", []);
    return result[0].toI32();
  }

  owner(): Address {
    let result = super.call("owner", []);
    return result[0].toAddress();
  }

  MINT_PROOF(): i32 {
    let result = super.call("MINT_PROOF", []);
    return result[0].toI32();
  }

  isOwner(): boolean {
    let result = super.call("isOwner", []);
    return result[0].toBoolean();
  }

  ace(): Address {
    let result = super.call("ace", []);
    return result[0].toAddress();
  }

  BURN_PROOF(): i32 {
    let result = super.call("BURN_PROOF", []);
    return result[0].toI32();
  }

  EIP712_DOMAIN_HASH(): Bytes {
    let result = super.call("EIP712_DOMAIN_HASH", []);
    return result[0].toBytes();
  }

  linkedToken(): Address {
    let result = super.call("linkedToken", []);
    return result[0].toAddress();
  }

  scalingFactor(): BigInt {
    let result = super.call("scalingFactor", []);
    return result[0].toBigInt();
  }
}

export class ConfidentialBurnCall extends EthereumCall {
  get inputs(): ConfidentialBurnCall__Inputs {
    return new ConfidentialBurnCall__Inputs(this);
  }

  get outputs(): ConfidentialBurnCall__Outputs {
    return new ConfidentialBurnCall__Outputs(this);
  }
}

export class ConfidentialBurnCall__Inputs {
  _call: ConfidentialBurnCall;

  constructor(call: ConfidentialBurnCall) {
    this._call = call;
  }

  get _proof(): i32 {
    return this._call.inputValues[0].value.toI32();
  }

  get _proofData(): Bytes {
    return this._call.inputValues[1].value.toBytes();
  }
}

export class ConfidentialBurnCall__Outputs {
  _call: ConfidentialBurnCall;

  constructor(call: ConfidentialBurnCall) {
    this._call = call;
  }
}

export class ConfidentialMintCall extends EthereumCall {
  get inputs(): ConfidentialMintCall__Inputs {
    return new ConfidentialMintCall__Inputs(this);
  }

  get outputs(): ConfidentialMintCall__Outputs {
    return new ConfidentialMintCall__Outputs(this);
  }
}

export class ConfidentialMintCall__Inputs {
  _call: ConfidentialMintCall;

  constructor(call: ConfidentialMintCall) {
    this._call = call;
  }

  get _proof(): i32 {
    return this._call.inputValues[0].value.toI32();
  }

  get _proofData(): Bytes {
    return this._call.inputValues[1].value.toBytes();
  }
}

export class ConfidentialMintCall__Outputs {
  _call: ConfidentialMintCall;

  constructor(call: ConfidentialMintCall) {
    this._call = call;
  }
}

export class ConfidentialApproveCall extends EthereumCall {
  get inputs(): ConfidentialApproveCall__Inputs {
    return new ConfidentialApproveCall__Inputs(this);
  }

  get outputs(): ConfidentialApproveCall__Outputs {
    return new ConfidentialApproveCall__Outputs(this);
  }
}

export class ConfidentialApproveCall__Inputs {
  _call: ConfidentialApproveCall;

  constructor(call: ConfidentialApproveCall) {
    this._call = call;
  }

  get _noteHash(): Bytes {
    return this._call.inputValues[0].value.toBytes();
  }

  get _spender(): Address {
    return this._call.inputValues[1].value.toAddress();
  }

  get _status(): boolean {
    return this._call.inputValues[2].value.toBoolean();
  }

  get _signature(): Bytes {
    return this._call.inputValues[3].value.toBytes();
  }
}

export class ConfidentialApproveCall__Outputs {
  _call: ConfidentialApproveCall;

  constructor(call: ConfidentialApproveCall) {
    this._call = call;
  }
}

export class UpgradeRegistryVersionCall extends EthereumCall {
  get inputs(): UpgradeRegistryVersionCall__Inputs {
    return new UpgradeRegistryVersionCall__Inputs(this);
  }

  get outputs(): UpgradeRegistryVersionCall__Outputs {
    return new UpgradeRegistryVersionCall__Outputs(this);
  }
}

export class UpgradeRegistryVersionCall__Inputs {
  _call: UpgradeRegistryVersionCall;

  constructor(call: UpgradeRegistryVersionCall) {
    this._call = call;
  }

  get _factoryId(): i32 {
    return this._call.inputValues[0].value.toI32();
  }
}

export class UpgradeRegistryVersionCall__Outputs {
  _call: UpgradeRegistryVersionCall;

  constructor(call: UpgradeRegistryVersionCall) {
    this._call = call;
  }
}

export class UpdateNoteMetaDataCall extends EthereumCall {
  get inputs(): UpdateNoteMetaDataCall__Inputs {
    return new UpdateNoteMetaDataCall__Inputs(this);
  }

  get outputs(): UpdateNoteMetaDataCall__Outputs {
    return new UpdateNoteMetaDataCall__Outputs(this);
  }
}

export class UpdateNoteMetaDataCall__Inputs {
  _call: UpdateNoteMetaDataCall;

  constructor(call: UpdateNoteMetaDataCall) {
    this._call = call;
  }

  get noteHash(): Bytes {
    return this._call.inputValues[0].value.toBytes();
  }

  get metaData(): Bytes {
    return this._call.inputValues[1].value.toBytes();
  }
}

export class UpdateNoteMetaDataCall__Outputs {
  _call: UpdateNoteMetaDataCall;

  constructor(call: UpdateNoteMetaDataCall) {
    this._call = call;
  }
}

export class RenounceOwnershipCall extends EthereumCall {
  get inputs(): RenounceOwnershipCall__Inputs {
    return new RenounceOwnershipCall__Inputs(this);
  }

  get outputs(): RenounceOwnershipCall__Outputs {
    return new RenounceOwnershipCall__Outputs(this);
  }
}

export class RenounceOwnershipCall__Inputs {
  _call: RenounceOwnershipCall;

  constructor(call: RenounceOwnershipCall) {
    this._call = call;
  }
}

export class RenounceOwnershipCall__Outputs {
  _call: RenounceOwnershipCall;

  constructor(call: RenounceOwnershipCall) {
    this._call = call;
  }
}

export class SetProofsCall extends EthereumCall {
  get inputs(): SetProofsCall__Inputs {
    return new SetProofsCall__Inputs(this);
  }

  get outputs(): SetProofsCall__Outputs {
    return new SetProofsCall__Outputs(this);
  }
}

export class SetProofsCall__Inputs {
  _call: SetProofsCall;

  constructor(call: SetProofsCall) {
    this._call = call;
  }

  get _epoch(): i32 {
    return this._call.inputValues[0].value.toI32();
  }

  get _proofs(): BigInt {
    return this._call.inputValues[1].value.toBigInt();
  }
}

export class SetProofsCall__Outputs {
  _call: SetProofsCall;

  constructor(call: SetProofsCall) {
    this._call = call;
  }
}

export class ConfidentialTransferCall extends EthereumCall {
  get inputs(): ConfidentialTransferCall__Inputs {
    return new ConfidentialTransferCall__Inputs(this);
  }

  get outputs(): ConfidentialTransferCall__Outputs {
    return new ConfidentialTransferCall__Outputs(this);
  }
}

export class ConfidentialTransferCall__Inputs {
  _call: ConfidentialTransferCall;

  constructor(call: ConfidentialTransferCall) {
    this._call = call;
  }

  get _proofData(): Bytes {
    return this._call.inputValues[0].value.toBytes();
  }

  get _signatures(): Bytes {
    return this._call.inputValues[1].value.toBytes();
  }
}

export class ConfidentialTransferCall__Outputs {
  _call: ConfidentialTransferCall;

  constructor(call: ConfidentialTransferCall) {
    this._call = call;
  }
}

export class ConfidentialTransferFromCall extends EthereumCall {
  get inputs(): ConfidentialTransferFromCall__Inputs {
    return new ConfidentialTransferFromCall__Inputs(this);
  }

  get outputs(): ConfidentialTransferFromCall__Outputs {
    return new ConfidentialTransferFromCall__Outputs(this);
  }
}

export class ConfidentialTransferFromCall__Inputs {
  _call: ConfidentialTransferFromCall;

  constructor(call: ConfidentialTransferFromCall) {
    this._call = call;
  }

  get _proof(): i32 {
    return this._call.inputValues[0].value.toI32();
  }

  get _proofOutput(): Bytes {
    return this._call.inputValues[1].value.toBytes();
  }
}

export class ConfidentialTransferFromCall__Outputs {
  _call: ConfidentialTransferFromCall;

  constructor(call: ConfidentialTransferFromCall) {
    this._call = call;
  }
}

export class TransferOwnershipCall extends EthereumCall {
  get inputs(): TransferOwnershipCall__Inputs {
    return new TransferOwnershipCall__Inputs(this);
  }

  get outputs(): TransferOwnershipCall__Outputs {
    return new TransferOwnershipCall__Outputs(this);
  }
}

export class TransferOwnershipCall__Inputs {
  _call: TransferOwnershipCall;

  constructor(call: TransferOwnershipCall) {
    this._call = call;
  }

  get newOwner(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class TransferOwnershipCall__Outputs {
  _call: TransferOwnershipCall;

  constructor(call: TransferOwnershipCall) {
    this._call = call;
  }
}
